language: perl
arch:
 - arm64
matrix:
 include:
  - dist: xenial
    perl: 5.24
    env: USE_SUDO=
  - dist: bionic
    perl: 5.26
    env: USE_SUDO=
  - dist: focal
    perl: 5.32
    env: USE_SUDO=
  - dist: focal
    env: USE_SYSTEM_PERL=1 USE_SUDO=sudo
    language: minimal
  - dist: bionic
    perl: 5.26
    env: USE_SUDO= WITH_ALL_PM_DEPS=1 WITH_STRACE=1
  - dist: focal
    env: USE_SYSTEM_PERL=1 USE_SUDO=sudo WITH_ALL_PM_DEPS=1 WITH_STRACE=1
    language: minimal

branches:
 except:
  - /appveyor/
  - /github-actions/
  - /doozer/

before_install:
 - if [ "$USE_SYSTEM_PERL" = "1" ]; then sudo apt-get update -qq; sudo apt-get install -qq cpanminus; fi
 # speed up installation with system perl
 - if [ "$USE_SYSTEM_PERL" = "1" -a "$WITH_ALL_PM_DEPS" = "1" ]; then sudo apt-get install -qq libdate-manip-perl libdatetime-timezone-perl libipc-run-perl libtext-diff-perl libtext-unidecode-perl libtime-moment-perl libxml-libxml-perl perl-tk; fi
 - if [ "$USE_SYSTEM_PERL" != "1" -a "$WITH_ALL_PM_DEPS" = "1" ]; then $USE_SUDO cpanm --quiet --notest Date::Manip IPC::Run Tk Text::Unidecode XML::LibXML XTerm::Conf DateTime::TimeZone Time::Moment Text::Diff; fi
 # user-level strace does not work on newer linux kernels
 # without fiddling with the ptrace_scope setting ---
 # so make sure to remove the strace test if WITH_STRACE
 # is not set.
 # With newer travis VMs (docker containers?) it's not possible to set ptrace_scope anymore
 #- if [ "$WITH_STRACE" = "1" -a "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install -qq strace; sudo sh -c 'echo 0 > /proc/sys/kernel/yama/ptrace_scope'; else rm t/strace_begin.t; fi

install:
 - $USE_SUDO cpanm --quiet --installdeps --notest . || (cat $HOME/.cpanm/work/*/build.log; false)
 - '[ "$USE_SUDO" = "" ] || rm -f MYMETA.*'

script:
 - perl Makefile.PL && env HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make disttest
