name: CI

on:
  push:
    branches-ignore:
      - '*travis*'
      - '*appveyor*'
      - '*doozer*'
  pull_request:

jobs:

  test_on_host:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       include:
         - os: 'ubuntu-20.04'
         - os: 'ubuntu-22.04'
         - os: 'ubuntu-24.04'
         - os: 'windows-latest'
    steps:
    - name: apt hacks
      # /etc/apt/sources.list should be sufficient; all the other repositories are possibly problematic
      run: |
        sudo rm -f /etc/apt/sources.list.d/*.list
        sudo apt-get update -qq
      if: "startsWith(matrix.os, 'ubuntu-')"
    - uses: taiki-e/checkout-action@v1

    - name: "perl dependency installation (ubuntu)"
      run: |
        sudo apt-get install -q --no-install-recommends -y cpanminus libdate-manip-perl libdatetime-timezone-perl libipc-run-perl libtext-diff-perl libtext-unidecode-perl libtime-moment-perl libxml-libxml-perl perl-tk
        cpanm --sudo --quiet --installdeps --notest .
      if: "startsWith(matrix.os, 'ubuntu-')"
    - name: "perl dependency installation (windows)"
      run: |
        cpanm --quiet --installdeps --notest .
      if: "startsWith(matrix.os, 'windows-')"

    - name: "enable strace"
      run: |
        sudo sh -c 'echo 0 > /proc/sys/kernel/yama/ptrace_scope'
      if: "startsWith(matrix.os, 'ubuntu-')"

    - name: "Build and test (ubuntu)"
      run: |
        set -e
        perl Makefile.PL
        HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make test
      if: "!startsWith(matrix.os,'windows-')"
    - name: "Build and test (windows)"
      run: |
        c:\strawberry\perl\bin\perl Makefile.PL
        c:\strawberry\c\bin\gmake
        c:\strawberry\c\bin\gmake test
      if: "startsWith(matrix.os, 'windows-')"

  test_in_container:
    name: "Test with perl ${{ matrix.perlimage }}"
    runs-on: ubuntu-latest
    container: perl:${{ matrix.perlimage }}
    strategy:
      matrix:
        include:
          - perlimage: 5.8.9-threaded-stretch
          - perlimage: 5.10.1-buster
          - perlimage: 5.12.5-stretch
          - perlimage: 5.14.4-stretch
          - perlimage: 5.16.3-buster
          - perlimage: 5.18.4-buster
          - perlimage: 5.22.4-stretch
          - perlimage: 5.36.0-slim-bullseye
            with_all_pm_deps: true
          - perlimage: 5.40.0-slim-bookworm
    steps:
    - name: apt hacks
      run: |
        set -e
        CODENAME=$(perl -nle '/^VERSION_CODENAME="?([^"]+)/ and $codename=$1; /^VERSION="\d+ \((.*)\)/ and $maybe_codename=$1; END { print $codename || $maybe_codename }' /etc/os-release)
        case "$CODENAME" in
          wheezy|jessie|stretch)
            echo "APT::Get::AllowUnauthenticated 1;" > /etc/apt/apt.conf.d/02allow-unsigned
            echo "deb [check-valid-until=no] http://archive.debian.org/debian $CODENAME main"                   >  /etc/apt/sources.list
            echo "deb [check-valid-until=no] http://archive.debian.org/debian-security/ $CODENAME/updates main" >> /etc/apt/sources.list
            ;;
        esac
    - uses: taiki-e/checkout-action@v1
    - name: "Maybe install optional dependencies"
      run: |
        set -e
        apt-get update -qq
        apt-get install -q --no-install-recommends -y build-essential libx11-dev libfreetype6-dev libxft-dev libpng-dev libz-dev libjpeg-dev libxml2-dev
        if ! which cpm >/dev/null
        then
          # https://github.com/skaji/cpm?tab=readme-ov-file#1-self-contained-version
          curl -fsSL https://raw.githubusercontent.com/skaji/cpm/main/cpm > /usr/local/bin/cpm
          chmod +x /usr/local/bin/cpm
        fi
        export MAKEFLAGS="-j4"
        if ! cpm install -g -v Date::Manip IPC::Run Tk Text::Unidecode XML::LibXML XTerm::Conf DateTime::TimeZone DateTime::Format::ISO8601 Time::Moment Text::Diff
        then
          cat ~/.perl-cpm/build.log
          false
        fi
      if: "${{ matrix.with_all_pm_deps }}"
    - name: Install dependencies
      run: |
        set -e
        cpanm --quiet --installdeps --notest . || ( cat /github/home/.cpanm/work/*/build.log; false )
    - name: Build and test
      run: |
        set -e
        perl Makefile.PL
        HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make test
